# Generated by Django 4.1.1 on 2022-09-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='user_id',
        ),
    ]
